### ISSUE TITLE
Support container queries

### ISSUE THREAD

**Issue by probablyup** [styled-components/typescript-styled-plugin#14]
Currently this code isn't understood

```css
container-type: inline-size;  // <- warning, "Unknown property: 'container-type'ts-styled-plugin(9999)"

.someChildren {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
};

@container (max-width: 10rem) { // <- error, "} expected ts-styled-plugin(9999)"
  .someChildren {
    flex-direction: column;
  }
}
```
